import type { Migration } from './migration-runner';
import type { AlinaDatabaseClient } from '../client';

export const INITIAL_SCHEMA_SURQL = `
-- Entity Tables
DEFINE TABLE IF NOT EXISTS user SCHEMALESS;
DEFINE TABLE IF NOT EXISTS workspace SCHEMALESS;
DEFINE TABLE IF NOT EXISTS conversation SCHEMALESS;
DEFINE TABLE IF NOT EXISTS message SCHEMALESS;
DEFINE TABLE IF NOT EXISTS task SCHEMALESS;
DEFINE TABLE IF NOT EXISTS task_step SCHEMALESS;
DEFINE TABLE IF NOT EXISTS agent SCHEMALESS;
DEFINE TABLE IF NOT EXISTS agent_run SCHEMALESS;
DEFINE TABLE IF NOT EXISTS tool SCHEMALESS;
DEFINE TABLE IF NOT EXISTS tool_call SCHEMALESS;
DEFINE TABLE IF NOT EXISTS approval SCHEMALESS;
DEFINE TABLE IF NOT EXISTS memory SCHEMALESS;
DEFINE TABLE IF NOT EXISTS file_reference SCHEMALESS;
DEFINE TABLE IF NOT EXISTS browser_session SCHEMALESS;
DEFINE TABLE IF NOT EXISTS audit_event SCHEMALESS;

-- Vector Index on Memory (Cosine Distance)
DEFINE INDEX IF NOT EXISTS idx_memory_embedding ON TABLE memory 
  FIELDS embedding HNSW DIMENSION 384 DISTANCE COSINE;

-- Graph Relation Tables
DEFINE TABLE IF NOT EXISTS owns SCHEMALESS TYPE RELATION FROM user TO workspace;
DEFINE TABLE IF NOT EXISTS started SCHEMALESS TYPE RELATION FROM user TO conversation;
DEFINE TABLE IF NOT EXISTS contains SCHEMALESS TYPE RELATION FROM conversation TO message;
DEFINE TABLE IF NOT EXISTS created SCHEMALESS TYPE RELATION FROM user TO task;
DEFINE TABLE IF NOT EXISTS contains_step SCHEMALESS TYPE RELATION FROM task TO task_step;
DEFINE TABLE IF NOT EXISTS executed_by SCHEMALESS TYPE RELATION FROM task TO agent_run;
DEFINE TABLE IF NOT EXISTS invoked SCHEMALESS TYPE RELATION FROM agent_run TO tool_call;
DEFINE TABLE IF NOT EXISTS used SCHEMALESS TYPE RELATION FROM tool_call TO tool;
DEFINE TABLE IF NOT EXISTS requires SCHEMALESS TYPE RELATION FROM task TO approval;
DEFINE TABLE IF NOT EXISTS remembers SCHEMALESS TYPE RELATION FROM user TO memory;
DEFINE TABLE IF NOT EXISTS produced SCHEMALESS TYPE RELATION FROM task TO file_reference;
DEFINE TABLE IF NOT EXISTS contains_file SCHEMALESS TYPE RELATION FROM workspace TO file_reference;
`;

export const migration001InitialSchema: Migration = {
  version: '001',
  name: 'initial_domain_schema',
  up: async (client: AlinaDatabaseClient) => {
    await client.applySchema(INITIAL_SCHEMA_SURQL);
  },
};
